// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    dcsc
    (
        init => init
        upgrade => upgrade
        files => files
        userFiles => user_files
        uploadFile => upload_file
        removeFile => remove_file
        getUploadedFiles => get_uploaded_files
        addTag => add_tag
        removeTag => remove_tag
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
